[build]
# Point to our `index.html`.
target = "web/index.html"
# Set the output directory for the web build.
dist = "target/trunk"

[serve]
# Open a browser tab once the initial build is complete.
open = true
# Use IPv4 first - prevents errors on Windows
addresses = ["127.0.0.1", "::1"]
